server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/nlrunner_db
    username: nlrunner
    password: nlrunner
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO.CLIENT.ID}
            client-secret: ${KAKAO.CLIENT.SECRET}
            redirect-uri: ${KAKAO.REDIRECT.URI}
            authorization-grant-type: authorization_code
            client-authentication-method: 'client_secret_post'
            client-name: kakao
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id
jwt:
  token: ${JWT.SECRET.KEY}

logging:
  level:
    root: info
    com.project.throw_wa: info
    org:
      springframework:
        security: info
cloud:
  aws:
    s3:
      bucket: bucket-throw.wa
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY_ID}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
